### ISSUE TITLE
Changing supervisors

### ISSUE THREAD

**Issue by sbarnwell** [cityofasheville/coa-converse#32]
Not sure if this will be an issue but wondering how conversations will be handled when supervisors change. Will a new supervisor inherit conversations from a past supervisor? In other words, will conversations stick to the employee that is the subject of the conversation or to the supervisor initiating the conversation?

**Comment by ejaxon** [comment]
Here's how it works now:

1. The supervisor ID associated with the review remains unchanged
2. The employee continues to have the same access as before.
3. The review will show up on the new supervisor's page (e.g., you should be able to see Frances' reviews of me from the testing period). HOWEVER, the new supervisor does NOT have the ability to modify the old review.
4. TBD: the previous supervisor MAY have permission to modify the review - need to test that.

We need to figure out if this is the way we want to do this (and do some testing to verify for certain that it all does work this way).

cc: @fruiz7

**Comment by sbarnwell** [comment]
Yes, I think items 1-3 make perfect sense, and item 4 does not really seem necessary. From the test conversations, it does appear to be working in that I can see the "blah blah" conversations you had while testing with Frances.
